<?xml version="1.0" encoding="utf-8"?><Database Name="Thinkbridge" Class="MemberDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-DMP47DL;Initial Catalog=Thinkbridge;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ThinkbridgeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblProducts" Member="tblProducts">
    <Type Name="tblProduct">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>